; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;;--port ${env:UPLOAD_PORT}


[env:esp32-p4-custom]
platform = espressif32
board = esp32-p4-lp-16-hmi ; lub inna definicja płyty dla P4
framework = arduino, espidf
; ESP32-P4 wymaga ESP-IDF 5.3 lub nowszego
platform_packages =
    framework-espidf@^3.50300.0
    toolchain-riscv32-esp@12.2.0+20230208
    toolchain-xtensa-esp-elf@12.2.0+20230208
board_build.mcu = esp32p4
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.psram_size = 32MB
board_build.partitions = partitions_16MB.csv
; Konfiguracja LVGL i sterowników
build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    ; Włącz wsparcie dla PSRAM w LVGL
    -D LV_MEM_CUSTOM=1
    -D LV_MEM_CUSTOM_INCLUDE="esp_heap_caps.h"
    -D LV_MEM_CUSTOM_ALLOC="heap_caps_malloc"
    -D LV_MEM_CUSTOM_FREE="heap_caps_free"
    -D LV_MEM_CUSTOM_REALLOC="heap_caps_realloc"
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=1






[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = esptool

upload_flags = 
    --before=default_reset
    --after=hard_reset
    --no-stub
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bblanchon/ArduinoJson@^6.21.3
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	lvgl/lvgl @ ^8.3.11
board_build.partitions = partitions.csv
board_build.f_flash = 80000000L
board_build.flash_mode = dio
build_flags = 
	-D USER_SETUP_LOADED=1
	-D ILI9341_2_DRIVER
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=240
	-D TFT_MISO=12
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=4
	-D TFT_BL=21
	-D TFT_BACKLIGHT_ON=HIGH
	-D LOAD_GLCD
	-D TFT_INVERSION_ON
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	-D LV_CONF_INCLUDE_SIMPLE
    -I src
; upload_port = /dev/ttyUSB0

extra_scripts = post:merge_bin.py
