// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_TabPage6;
extern lv_obj_t * ui_TabPage7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Clock;
extern lv_obj_t * uic_main;
extern lv_obj_t * uic_znak;
extern lv_obj_t * uic_IP;
extern lv_obj_t * uic_clock;
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_label_aprs_data;
extern lv_obj_t * uic_label_pota_data;
extern lv_obj_t * uic_label_wwff_data;
extern lv_obj_t * uic_label_sonde_data;
extern lv_obj_t * uic_new_version;
extern lv_obj_t * uic_label_utc;
extern lv_obj_t * uic_pota;
extern lv_obj_t * uic_wwff;
extern lv_obj_t * uic_aprs;
extern lv_obj_t * uic_propa;
extern lv_obj_t * uic_sondy;
extern lv_obj_t * uic_konf;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

