// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_1024x600

#include "ui.h"

lv_obj_t * uic_konf;
lv_obj_t * uic_sondy;
lv_obj_t * uic_propa;
lv_obj_t * uic_aprs;
lv_obj_t * uic_wwff;
lv_obj_t * uic_pota;
lv_obj_t * uic_label_utc;
lv_obj_t * uic_new_version;
lv_obj_t * uic_label_sonde_data;
lv_obj_t * uic_label_wwff_data;
lv_obj_t * uic_label_pota_data;
lv_obj_t * uic_label_aprs_data;
lv_obj_t * uic_date;
lv_obj_t * uic_clock;
lv_obj_t * uic_IP;
lv_obj_t * uic_znak;
lv_obj_t * uic_main;
lv_obj_t * uic_Clock;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_TabPage4 = NULL;
lv_obj_t * ui_TabPage5 = NULL;
lv_obj_t * ui_TabPage6 = NULL;
lv_obj_t * ui_TabPage7 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_BOTTOM, 30);
    lv_obj_set_width(ui_TabView1, lv_pct(100));
    lv_obj_set_height(ui_TabView1, lv_pct(100));
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_TabView1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Main");
    lv_obj_clear_flag(ui_TabPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -337);
    lv_obj_set_y(ui_Label1, -251);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SQ5PGC");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x090808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 9);
    lv_obj_set_y(ui_Label2, -9);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label2, "255.255.255.255");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 243);
    lv_obj_set_y(ui_Label3, -249);
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "00:00:00");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xBB3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 109);
    lv_obj_set_y(ui_Label4, -249);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Poniedzialek, 01-01-2026");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -12);
    lv_obj_set_y(ui_Label5, -131);
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "APRS");

    ui_Label6 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 38);
    lv_obj_set_y(ui_Label6, -205);
    lv_obj_set_align(ui_Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label6, "POTA");

    ui_Label7 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 36);
    lv_obj_set_y(ui_Label7, -183);
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "WWFF");

    ui_Label8 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 38);
    lv_obj_set_y(ui_Label8, 104);
    lv_label_set_text(ui_Label8, "SONDA");

    ui_Label9 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 231);
    lv_obj_set_y(ui_Label9, 8);
    lv_label_set_text(ui_Label9, "");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xF10726), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -26);
    lv_obj_set_y(ui_Label10, -242);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "UTC");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x0F157C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -440);
    lv_obj_set_y(ui_Label11, 131);
    lv_obj_set_align(ui_Label11, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label11, "APRS");

    ui_Label12 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -10);
    lv_obj_set_y(ui_Label12, 53);
    lv_label_set_text(ui_Label12, "POTA");

    ui_Label13 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -13);
    lv_obj_set_y(ui_Label13, 75);
    lv_label_set_text(ui_Label13, "WWFF");

    ui_Label14 = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -12);
    lv_obj_set_y(ui_Label14, 103);
    lv_label_set_text(ui_Label14, "SONDA");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "POTA");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "WWFF");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "APRS");

    ui_TabPage5 = lv_tabview_add_tab(ui_TabView1, "PROPA");

    ui_TabPage6 = lv_tabview_add_tab(ui_TabView1, "SONDY");

    ui_TabPage7 = lv_tabview_add_tab(ui_TabView1, "KONF");

    uic_Clock = ui_Screen1;
    uic_main = ui_TabPage1;
    uic_znak = ui_Label1;
    uic_IP = ui_Label2;
    uic_clock = ui_Label3;
    uic_date = ui_Label4;
    uic_label_aprs_data = ui_Label5;
    uic_label_pota_data = ui_Label6;
    uic_label_wwff_data = ui_Label7;
    uic_label_sonde_data = ui_Label8;
    uic_new_version = ui_Label9;
    uic_label_utc = ui_Label10;
    uic_pota = ui_TabPage2;
    uic_wwff = ui_TabPage3;
    uic_aprs = ui_TabPage4;
    uic_propa = ui_TabPage5;
    uic_sondy = ui_TabPage6;
    uic_konf = ui_TabPage7;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Clock = NULL;
    ui_Screen1 = NULL;
    ui_TabView1 = NULL;
    uic_main = NULL;
    ui_TabPage1 = NULL;
    uic_znak = NULL;
    ui_Label1 = NULL;
    uic_IP = NULL;
    ui_Label2 = NULL;
    uic_clock = NULL;
    ui_Label3 = NULL;
    uic_date = NULL;
    ui_Label4 = NULL;
    uic_label_aprs_data = NULL;
    ui_Label5 = NULL;
    uic_label_pota_data = NULL;
    ui_Label6 = NULL;
    uic_label_wwff_data = NULL;
    ui_Label7 = NULL;
    uic_label_sonde_data = NULL;
    ui_Label8 = NULL;
    uic_new_version = NULL;
    ui_Label9 = NULL;
    uic_label_utc = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    uic_pota = NULL;
    ui_TabPage2 = NULL;
    uic_wwff = NULL;
    ui_TabPage3 = NULL;
    uic_aprs = NULL;
    ui_TabPage4 = NULL;
    uic_propa = NULL;
    ui_TabPage5 = NULL;
    uic_sondy = NULL;
    ui_TabPage6 = NULL;
    uic_konf = NULL;
    ui_TabPage7 = NULL;

}
